services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

    
  backend:
    depends_on:
      db:
        condition: service_started
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"


      
    
    
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD:  ${DATABASE_PASSWORD}
      MARIADB_DATABASE: uniplanner 
    ports:
      - "3307:3306"




